/* ============================================================================
   manifest.js — the module registry.

   THIS IS A DATA FILE. Adding a module means adding a row to CURRICULUM.md,
   an entry to the `modules` array below, and a file at
   content/modules/<id>.js. No file in assets/ or index.html changes.

   status:
     planned  — no content file yet; the site renders a placeholder from `scope`
     drafting — content file exists but is incomplete
     written  — complete and conforms to STYLE-CONTRACT.md
     frozen   — reviewed and approved; must not be restructured by later work

   A module is only fetched when it is opened (or during the idle-time search
   prefetch), so this list can grow to the full curriculum without slowing the
   first render.
   ========================================================================= */

window.CSPREP_MANIFEST = {

  site: {
    title: "Zero to Production Backend Engineering in C# / .NET",
    shortTitle: "Zero to Production",
    subtitle: "C# / .NET 10",
    netVersion: "10",
    blurb: "A single-folder, offline curriculum that starts at “what is a variable” and ends at reasoning about production systems under load. Every term is defined at first use. Nothing is hand-waved."
  },

  tracks: [
    { number: 1, title: "Language Foundations",
      blurb: "Start at “what is a variable” and finish able to read and write idiomatic modern C# and reason about how the type system actually behaves." },
    { number: 2, title: "Async, Memory, and Performance Internals",
      blurb: "Threads, the async state machine, garbage collection, and zero-allocation work — the track that separates using async from explaining a production incident." },
    { number: 3, title: "Web APIs and the Request Pipeline",
      blurb: "From a raw socket to a versioned, validated, observable HTTP API, with the middleware pipeline and DI lifetimes understood rather than copied." },
    { number: 4, title: "Data",
      blurb: "Relational modelling, SQL that survives an execution plan, EF Core without the N+1 surprises, transactions, and caching that stays correct." },
    { number: 5, title: "Production Systems and Architecture",
      blurb: "Architecture, resilience, security, observability, testing, and deployment — what it takes to run a service other people depend on." },
    { number: 6, title: "Data Structures, Algorithms, and Interview Problems",
      blurb: "Complexity from first principles and every major algorithmic pattern, organised so unseen interview problems are attackable." }
  ],

  modules: [
    /* -- Track 1: Language Foundations ---------------------------------------- */
    { id: "t1-01-what-a-program-is",
      track: 1, number: 1, minutes: 50, status: "written",
      title: "What a Program Actually Is",
      scope: "Source code, compilation, the CLR, IL, JIT, and what happens between double-clicking and output." },
    { id: "t1-02-variables-and-types",
      track: 1, number: 2, minutes: 55, status: "written",
      title: "Variables and Types",
      scope: "Named boxes for data, why types exist, the built-in primitives, var, and type inference." },
    { id: "t1-03-value-vs-reference",
      track: 1, number: 3, minutes: 55, status: "frozen",
      title: "Value Types vs Reference Types",
      scope: "Stack, heap, what copying means, boxing, mutable-struct traps, and why this underlies everything later." },
    { id: "t1-04-control-flow",
      track: 1, number: 4, minutes: 55, status: "written",
      title: "Control Flow",
      scope: "if/else, switch, loops, break/continue, and how branching compiles down." },
    { id: "t1-05-methods-and-parameters",
      track: 1, number: 5, minutes: 55, status: "written",
      title: "Methods, Arguments, and Parameters",
      scope: "Signatures, overloads, ref/out/in, optional and named arguments, params." },
    { id: "t1-06-arrays",
      track: 1, number: 6, minutes: 55, status: "written",
      title: "Arrays",
      scope: "Fixed-size contiguous storage, bounds checking, multidimensional vs jagged, and their cost model." },
    { id: "t1-07-strings-and-interning",
      track: 1, number: 7, minutes: 55, status: "written",
      title: "Strings, Immutability, and Interning",
      scope: "UTF-16 internals, immutability, the intern pool, StringBuilder, and comparison/culture pitfalls." },
    { id: "t1-08-classes-and-objects",
      track: 1, number: 8, minutes: 55, status: "written",
      title: "Classes and Objects",
      scope: "Blueprint vs instance, fields, constructors, object initialisers, this, and object lifetime." },
    { id: "t1-09-encapsulation",
      track: 1, number: 9, minutes: 55, status: "written",
      title: "Encapsulation and Access Modifiers",
      scope: "Why hiding state is not bureaucracy, properties vs fields, private/internal/protected/public/file." },
    { id: "t1-10-inheritance",
      track: 1, number: 10, minutes: 55, status: "written",
      title: "Inheritance",
      scope: "Type hierarchies, base calls, constructor chaining, and the fragile base class problem." },
    { id: "t1-11-polymorphism",
      track: 1, number: 11, minutes: 55, status: "written",
      title: "Polymorphism and Virtual Dispatch",
      scope: "virtual/override/new/sealed, the vtable, and what dispatch costs." },
    { id: "t1-12-abstraction-and-interfaces",
      track: 1, number: 12, minutes: 55, status: "written",
      title: "Abstraction, Abstract Classes, and Interfaces",
      scope: "abstract vs virtual vs sealed, interface contracts, default interface methods, explicit implementation." },
    { id: "t1-13-composition-over-inheritance",
      track: 1, number: 13, minutes: 55, status: "written",
      title: "Composition Over Inheritance",
      scope: "Why deep hierarchies rot, delegation, and rewriting an inheritance tree as composition." },
    { id: "t1-14-static-and-lifetime",
      track: 1, number: 14, minutes: 55, status: "written",
      title: "Static Members, Constructors, and Lifetime",
      scope: "static state, static constructors and their threading guarantees, and why static mutable state hurts." },
    { id: "t1-15-structs-and-records",
      track: 1, number: 15, minutes: 55, status: "written",
      title: "Structs, Records, readonly, and init",
      scope: "record class vs record struct, readonly struct, init accessors, with expressions, value equality." },
    { id: "t1-16-equality-and-hashing",
      track: 1, number: 16, minutes: 55, status: "written",
      title: "Equality, GetHashCode, and Comparers",
      scope: "Reference vs value equality, the hashcode contract, IEquatable<T>, IComparer<T>, and dictionary corruption." },
    { id: "t1-17-generics",
      track: 1, number: 17, minutes: 55, status: "written",
      title: "Generics",
      scope: "Type parameters, why they beat object, JIT specialisation for value types, variance basics." },
    { id: "t1-18-generic-constraints",
      track: 1, number: 18, minutes: 55, status: "written",
      title: "Generic Constraints",
      scope: "where clauses, new(), notnull, unmanaged, struct/class, and static abstract members in interfaces." },
    { id: "t1-19-collections-overview",
      track: 1, number: 19, minutes: 55, status: "written",
      title: "Collections and Their Cost Model",
      scope: "List, Dictionary, HashSet, Queue, Stack, SortedDictionary, arrays — and when each is the wrong choice." },
    { id: "t1-20-ienumerable-vs-icollection",
      track: 1, number: 20, minutes: 55, status: "written",
      title: "IEnumerable vs ICollection vs IList vs IReadOnly*",
      scope: "The interface hierarchy, what each guarantees, which members exist where, and choosing return types." },
    { id: "t1-21-delegates",
      track: 1, number: 21, minutes: 55, status: "written",
      title: "Delegates",
      scope: "Function pointers with a type, Func/Action/Predicate, multicast delegates, and invocation cost." },
    { id: "t1-22-lambdas-and-closures",
      track: 1, number: 22, minutes: 55, status: "written",
      title: "Lambdas and Closures",
      scope: "Capture semantics, the compiler-generated closure class, allocation, and the captured-loop-variable trap." },
    { id: "t1-23-events",
      track: 1, number: 23, minutes: 55, status: "written",
      title: "Events",
      scope: "The publish/subscribe pattern, event vs delegate field, the event-handler memory leak, and safe raising." },
    { id: "t1-24-linq-fundamentals",
      track: 1, number: 24, minutes: 55, status: "written",
      title: "LINQ: Both Syntaxes",
      scope: "Query vs method syntax, the standard operators, and how query syntax lowers to method calls." },
    { id: "t1-25-deferred-execution",
      track: 1, number: 25, minutes: 55, status: "written",
      title: "Deferred Execution and the Cost of LINQ",
      scope: "Lazy pipelines, multiple enumeration, closure capture in queries, allocation cost, and when to write a loop." },
    { id: "t1-26-iterators-and-yield",
      track: 1, number: 26, minutes: 55, status: "written",
      title: "Iterators and yield",
      scope: "Writing your own lazy sequences, the generated state machine, try/finally semantics, and streaming." },
    { id: "t1-27-pattern-matching",
      track: 1, number: 27, minutes: 55, status: "written",
      title: "Pattern Matching",
      scope: "Type, constant, relational, logical, property, positional, and list patterns; switch expressions; exhaustiveness." },
    { id: "t1-28-nullable-reference-types",
      track: 1, number: 28, minutes: 55, status: "written",
      title: "Nullable Reference Types",
      scope: "The ? annotation, flow analysis, !, nullable attributes, and migrating a codebase without lying to the compiler." },
    { id: "t1-29-exceptions",
      track: 1, number: 29, minutes: 55, status: "written",
      title: "Exceptions and Exception Design",
      scope: "Throwing, catching, filters, finally, custom exception types, cost, and when *not* to use exceptions." },
    { id: "t1-30-extension-methods",
      track: 1, number: 30, minutes: 55, status: "written",
      title: "Extension Methods",
      scope: "Static methods that read like instance methods, resolution rules, and when they become a maintenance problem." },
    { id: "t1-31-reflection-and-attributes",
      track: 1, number: 31, minutes: 55, status: "written",
      title: "Reflection and Attributes",
      scope: "Metadata at runtime, Type, MethodInfo, writing and reading attributes, cost, and trimming/AOT hazards." },
    { id: "t1-32-source-generators",
      track: 1, number: 32, minutes: 55, status: "written",
      title: "Source Generators",
      scope: "Compile-time code generation, incremental generators, when they replace reflection, and debugging them." },

    /* -- Track 2: Async, Memory, and Performance Internals -------------------- */
    { id: "t2-01-threads-and-scheduling",
      track: 2, number: 1, minutes: 55, status: "written",
      title: "Threads, Cores, and the OS Scheduler",
      scope: "What a thread physically is, context switching, concurrency vs parallelism, and why threads are expensive." },
    { id: "t2-02-thread-pool",
      track: 2, number: 2, minutes: 45, status: "planned",
      title: "The Thread Pool",
      scope: "Work queues, local vs global queues, work stealing, hill-climbing injection, and starvation." },
    { id: "t2-03-what-async-really-is",
      track: 2, number: 3, minutes: 45, status: "planned",
      title: "What async Actually Is",
      scope: "Async as *not occupying a thread while waiting*, I/O completion ports, and the lie that async means parallel." },
    { id: "t2-04-task-and-valuetask",
      track: 2, number: 4, minutes: 45, status: "planned",
      title: "Task, Task<T>, and ValueTask<T>",
      scope: "Promise semantics, completion sources, when ValueTask is worth it, and its consumption rules." },
    { id: "t2-05-async-state-machine",
      track: 2, number: 5, minutes: 45, status: "planned",
      title: "The async/await State Machine",
      scope: "Reading the compiler-generated struct, MoveNext, awaiters, and what each await actually costs." },
    { id: "t2-06-synchronizationcontext",
      track: 2, number: 6, minutes: 45, status: "planned",
      title: "SynchronizationContext and ConfigureAwait",
      scope: "Context capture, why ASP.NET Core has no context, when ConfigureAwait(false) matters, and library rules." },
    { id: "t2-07-sync-over-async-deadlocks",
      track: 2, number: 7, minutes: 45, status: "planned",
      title: "Deadlocks and Sync-Over-Async",
      scope: ".Result/.Wait(), the classic deadlock, thread-pool exhaustion, and how to actually fix a blocking call." },
    { id: "t2-08-cancellation",
      track: 2, number: 8, minutes: 45, status: "planned",
      title: "Cancellation Tokens",
      scope: "Cooperative cancellation, linked sources, timeouts, and threading tokens end to end through a request." },
    { id: "t2-09-iasyncenumerable",
      track: 2, number: 9, minutes: 45, status: "planned",
      title: "IAsyncEnumerable<T>",
      scope: "Async streams, await foreach, cancellation in streams, and streaming a query result without buffering." },
    { id: "t2-10-parallelism",
      track: 2, number: 10, minutes: 45, status: "planned",
      title: "Parallelism: Parallel, PLINQ, and Task.WhenAll",
      scope: "CPU-bound work, partitioning, degree of parallelism, and why parallel is not always faster." },
    { id: "t2-11-race-conditions",
      track: 2, number: 11, minutes: 45, status: "planned",
      title: "Race Conditions and Memory Visibility",
      scope: "Interleaving, torn reads, the memory model, volatile, and why \"it works on my machine\" is meaningless here." },
    { id: "t2-12-locking",
      track: 2, number: 12, minutes: 45, status: "planned",
      title: "lock, Monitor, and Lock Design",
      scope: "Mutual exclusion, lock granularity, lock ordering, deadlock avoidance, and System.Threading.Lock in .NET 9+." },
    { id: "t2-13-interlocked-and-lockfree",
      track: 2, number: 13, minutes: 45, status: "planned",
      title: "Interlocked and Lock-Free Basics",
      scope: "Atomic operations, compare-and-swap, spin waiting, and when lock-free is a mistake." },
    { id: "t2-14-async-coordination",
      track: 2, number: 14, minutes: 45, status: "planned",
      title: "SemaphoreSlim, Channels, and Async Coordination",
      scope: "Async-safe throttling, producer/consumer with System.Threading.Channels, and bounded backpressure." },
    { id: "t2-15-concurrent-collections",
      track: 2, number: 15, minutes: 45, status: "planned",
      title: "Concurrent Collections",
      scope: "ConcurrentDictionary and friends, their atomicity guarantees, GetOrAdd re-entrancy, and when to just lock." },
    { id: "t2-16-gc-fundamentals",
      track: 2, number: 16, minutes: 45, status: "planned",
      title: "Garbage Collection Fundamentals",
      scope: "Managed heap, roots, mark/sweep/compact, generations 0/1/2, and what a collection pauses." },
    { id: "t2-17-gc-tuning",
      track: 2, number: 17, minutes: 45, status: "planned",
      title: "LOH, Server vs Workstation GC, and Allocation Pressure",
      scope: "Large object heap, fragmentation, GC modes, GCSettings, DATAS in .NET 8+, and reading GC counters." },
    { id: "t2-18-finalisers-and-idisposable",
      track: 2, number: 18, minutes: 45, status: "planned",
      title: "IDisposable, IAsyncDisposable, and Finalisers",
      scope: "Deterministic cleanup, the dispose pattern, using declarations, and why finalisers are a last resort." },
    { id: "t2-19-span-and-memory",
      track: 2, number: 19, minutes: 45, status: "planned",
      title: "Span<T> and Memory<T>",
      scope: "Stack-only slices, ref struct rules, slicing without allocating, and where Memory<T> is required instead." },
    { id: "t2-20-zero-allocation",
      track: 2, number: 20, minutes: 45, status: "planned",
      title: "Zero-Allocation Techniques",
      scope: "stackalloc, ArrayPool<T>, ObjectPool, SearchValues, and rewriting a hot path to allocate nothing." },
    { id: "t2-21-string-without-allocation",
      track: 2, number: 21, minutes: 45, status: "planned",
      title: "String Handling Without Allocation",
      scope: "ReadOnlySpan<char>, string.Create, interpolated string handlers, UTF-8 literals, and parsing in place." },
    { id: "t2-22-streams-and-buffering",
      track: 2, number: 22, minutes: 45, status: "planned",
      title: "Streams, Buffering, and Async I/O",
      scope: "Stream contracts, buffer sizing, PipeReader vs Stream, and copying files without wasting memory." },
    { id: "t2-23-pipelines",
      track: 2, number: 23, minutes: 45, status: "planned",
      title: "System.IO.Pipelines",
      scope: "Why parsing network data with Stream is hard, back-pressure, SequenceReader, and a real protocol parser." },
    { id: "t2-24-benchmarkdotnet",
      track: 2, number: 24, minutes: 45, status: "planned",
      title: "Benchmarking with BenchmarkDotNet",
      scope: "Harness setup, warmup, memory diagnosers, reading the output honestly, and the benchmarks that lie." },
    { id: "t2-25-diagnostics-tooling",
      track: 2, number: 25, minutes: 45, status: "planned",
      title: "Profiling and Production Diagnostics",
      scope: "dotnet-counters, dotnet-trace, dotnet-dump, dotnet-gcdump, and walking a real memory dump." },

    /* -- Track 3: Web APIs and the Request Pipeline --------------------------- */
    { id: "t3-01-http-fundamentals",
      track: 3, number: 1, minutes: 40, status: "planned",
      title: "HTTP As It Actually Behaves",
      scope: "Methods, status codes, headers, content negotiation, keep-alive, HTTP/2 and /3, and idempotency/safety semantics." },
    { id: "t3-02-hosting-model",
      track: 3, number: 2, minutes: 40, status: "planned",
      title: "The Hosting Model",
      scope: "WebApplication, the generic host, service registration vs pipeline building, startup order, graceful shutdown." },
    { id: "t3-03-kestrel",
      track: 3, number: 3, minutes: 40, status: "planned",
      title: "Kestrel",
      scope: "The socket-to-request path, connection limits, request limits, timeouts, TLS, and reverse-proxy deployment." },
    { id: "t3-04-middleware-pipeline",
      track: 3, number: 4, minutes: 40, status: "planned",
      title: "The Middleware Pipeline",
      scope: "Ordering as behaviour, Use/Run/Map, short-circuiting, writing custom middleware, and terminal middleware." },
    { id: "t3-05-routing",
      track: 3, number: 5, minutes: 40, status: "planned",
      title: "Routing and Endpoints",
      scope: "Route templates, constraints, endpoint metadata, route groups, and link generation." },
    { id: "t3-06-minimal-vs-controllers",
      track: 3, number: 6, minutes: 40, status: "planned",
      title: "Minimal APIs vs Controllers",
      scope: "The real trade-offs — testability, filters, conventions, discoverability — with an honest recommendation." },
    { id: "t3-07-model-binding",
      track: 3, number: 7, minutes: 40, status: "planned",
      title: "Model Binding",
      scope: "Sources, binding rules, custom binders, [AsParameters], and binding failures that silently produce nulls." },
    { id: "t3-08-validation",
      track: 3, number: 8, minutes: 40, status: "planned",
      title: "Validation",
      scope: "Data annotations, IValidatableObject, FluentValidation, minimal-API validation in .NET 10, and layering rules." },
    { id: "t3-09-problem-details",
      track: 3, number: 9, minutes: 40, status: "planned",
      title: "ProblemDetails and Error Contracts",
      scope: "RFC 9457, exception handling middleware, a consistent error envelope, and never leaking internals." },
    { id: "t3-10-dependency-injection",
      track: 3, number: 10, minutes: 40, status: "planned",
      title: "Dependency Injection",
      scope: "Inversion of control from first principles, the container, constructor injection, and composition roots." },
    { id: "t3-11-di-lifetimes",
      track: 3, number: 11, minutes: 40, status: "planned",
      title: "DI Lifetimes and the Bugs They Cause",
      scope: "Singleton/scoped/transient, captive dependencies, scope in background services, and DbContext disasters." },
    { id: "t3-12-configuration",
      track: 3, number: 12, minutes: 40, status: "planned",
      title: "Configuration",
      scope: "Providers, precedence, binding, reloading, and configuration that differs per environment." },
    { id: "t3-13-options-pattern",
      track: 3, number: 13, minutes: 40, status: "planned",
      title: "The Options Pattern",
      scope: "IOptions vs IOptionsSnapshot vs IOptionsMonitor, validation on startup, and named options." },
    { id: "t3-14-secrets",
      track: 3, number: 14, minutes: 40, status: "planned",
      title: "Environments and Secret Handling",
      scope: "User secrets, environment variables, key vaults, what must never reach source control, and rotation." },
    { id: "t3-15-api-versioning",
      track: 3, number: 15, minutes: 40, status: "planned",
      title: "API Versioning",
      scope: "URL vs header vs media-type versioning, deprecation, and evolving a contract without breaking clients." },
    { id: "t3-16-pagination",
      track: 3, number: 16, minutes: 40, status: "planned",
      title: "Pagination, Filtering, and Sorting",
      scope: "Offset vs keyset pagination, stable ordering, filter contracts, and not letting clients DoS your database." },
    { id: "t3-17-file-upload",
      track: 3, number: 17, minutes: 40, status: "planned",
      title: "File Upload and Storage",
      scope: "Multipart handling, streaming large uploads, size limits, content sniffing, virus scanning, and blob storage." },
    { id: "t3-18-openapi",
      track: 3, number: 18, minutes: 40, status: "planned",
      title: "OpenAPI and Documentation",
      scope: "Built-in OpenAPI in .NET 9+/10, schema shaping, examples, and keeping docs honest." },
    { id: "t3-19-health-checks",
      track: 3, number: 19, minutes: 40, status: "planned",
      title: "Health Checks",
      scope: "Liveness vs readiness vs startup, dependency checks, and the health check that took down the cluster." },
    { id: "t3-20-feature-flags",
      track: 3, number: 20, minutes: 40, status: "planned",
      title: "Feature Flags",
      scope: "Toggle types, Microsoft.FeatureManagement, targeting filters, flag lifecycle, and removing dead flags." },
    { id: "t3-21-hosted-services",
      track: 3, number: 21, minutes: 40, status: "planned",
      title: "IHostedService and BackgroundService",
      scope: "Lifetime hooks, long-running loops, scope creation, exception handling, and graceful shutdown." },
    { id: "t3-22-scheduled-jobs",
      track: 3, number: 22, minutes: 40, status: "planned",
      title: "Scheduled and Queued Jobs: Hangfire and Quartz",
      scope: "Persistent job storage, retries, cron scheduling, distributed execution, and job idempotency." },
    { id: "t3-23-signalr",
      track: 3, number: 23, minutes: 40, status: "planned",
      title: "Real-Time with SignalR",
      scope: "Hubs, transports and fallback, groups, scale-out with a backplane, and connection lifecycle handling." },
    { id: "t3-24-grpc",
      track: 3, number: 24, minutes: 40, status: "planned",
      title: "gRPC",
      scope: "Protobuf contracts, the four call types, code generation, deadlines, interceptors, and when to prefer REST." },
    { id: "t3-25-http-client",
      track: 3, number: 25, minutes: 40, status: "planned",
      title: "Calling Other Services: HttpClient",
      scope: "IHttpClientFactory, socket exhaustion, handler lifetime, typed clients, and timeout layering." },
    { id: "t3-26-webhooks-outbound",
      track: 3, number: 26, minutes: 40, status: "planned",
      title: "Sending Webhooks",
      scope: "Signing payloads (HMAC), timestamps, retries with backoff, delivery logs, and consumer-friendly design." },
    { id: "t3-27-webhooks-inbound",
      track: 3, number: 27, minutes: 40, status: "planned",
      title: "Consuming Webhooks Safely",
      scope: "Signature verification, replay protection, constant-time comparison, idempotent handling, and fast ACK." },

    /* -- Track 4: Data -------------------------------------------------------- */
    { id: "t4-01-relational-modelling",
      track: 4, number: 1, minutes: 40, status: "planned",
      title: "Relational Modelling From Scratch",
      scope: "Tables, rows, keys, relationships, normal forms, and modelling a real domain end to end." },
    { id: "t4-02-sql-basics",
      track: 4, number: 2, minutes: 40, status: "planned",
      title: "SQL: Reading and Filtering",
      scope: "SELECT, WHERE, ORDER BY, NULL semantics, and the three-valued logic that catches everyone." },
    { id: "t4-03-joins",
      track: 4, number: 3, minutes: 40, status: "planned",
      title: "Joins",
      scope: "Inner, left, right, full, cross, self, and anti-joins — with the row-multiplication trap." },
    { id: "t4-04-grouping",
      track: 4, number: 4, minutes: 40, status: "planned",
      title: "Grouping and Aggregation",
      scope: "GROUP BY, HAVING, aggregate semantics with NULL, and grouping sets." },
    { id: "t4-05-window-functions",
      track: 4, number: 5, minutes: 40, status: "planned",
      title: "Window Functions",
      scope: "OVER, partitioning, ranking, running totals, LAG/LEAD, and de-duplication patterns." },
    { id: "t4-06-ctes-and-recursion",
      track: 4, number: 6, minutes: 40, status: "planned",
      title: "CTEs and Recursive Queries",
      scope: "Readability, materialisation, recursive hierarchies, and cycle protection." },
    { id: "t4-07-indexes",
      track: 4, number: 7, minutes: 40, status: "planned",
      title: "Indexes",
      scope: "B-trees, clustered vs non-clustered, composite key order, covering indexes, and the write-cost trade-off." },
    { id: "t4-08-execution-plans",
      track: 4, number: 8, minutes: 40, status: "planned",
      title: "Execution Plans and Why a Query Is Slow",
      scope: "Reading a plan, scans vs seeks, estimated vs actual rows, parameter sniffing, and SARGability." },
    { id: "t4-09-transactions",
      track: 4, number: 9, minutes: 40, status: "planned",
      title: "Transactions and ACID",
      scope: "Atomicity in practice, transaction scope, long transactions, and what a rollback does not undo." },
    { id: "t4-10-isolation-levels",
      track: 4, number: 10, minutes: 40, status: "planned",
      title: "Isolation Levels and Their Anomalies",
      scope: "Dirty/non-repeatable/phantom reads, write skew, snapshot isolation, and picking a level deliberately." },
    { id: "t4-11-concurrency-control",
      track: 4, number: 11, minutes: 40, status: "planned",
      title: "Optimistic and Pessimistic Concurrency",
      scope: "Row versions, ETags, UPDATE ... WHERE version =, explicit locks, and conflict resolution UX." },
    { id: "t4-12-connection-pooling",
      track: 4, number: 12, minutes: 40, status: "planned",
      title: "Connection Pooling",
      scope: "Pool mechanics, pool exhaustion symptoms, connection string tuning, and leaked connections." },
    { id: "t4-13-orms-what-they-hide",
      track: 4, number: 13, minutes: 40, status: "planned",
      title: "ORMs and What They Hide",
      scope: "Impedance mismatch, generated SQL, leaky abstractions, and the cost you accept when you adopt one." },
    { id: "t4-14-efcore-dbcontext",
      track: 4, number: 14, minutes: 40, status: "planned",
      title: "EF Core: DbContext and Configuration Approaches",
      scope: "Data annotations vs fluent API vs IEntityTypeConfiguration, and why one scales better." },
    { id: "t4-15-efcore-change-tracking",
      track: 4, number: 15, minutes: 40, status: "planned",
      title: "EF Core: Change Tracking",
      scope: "The identity map, entity states, SaveChanges mechanics, and tracking bugs in long-lived contexts." },
    { id: "t4-16-efcore-relationships",
      track: 4, number: 16, minutes: 40, status: "planned",
      title: "EF Core: Relationship Configuration",
      scope: "One-to-one, one-to-many, many-to-many, owned types, and cascade delete behaviour." },
    { id: "t4-17-efcore-inheritance",
      track: 4, number: 17, minutes: 40, status: "planned",
      title: "EF Core: Inheritance Mapping",
      scope: "TPH, TPT, TPC — storage shape, query cost, and discriminator configuration." },
    { id: "t4-18-efcore-querying",
      track: 4, number: 18, minutes: 40, status: "planned",
      title: "EF Core: Querying, Tracking, and N+1",
      scope: "AsNoTracking, split queries, eager vs lazy loading, projection, and diagnosing N+1 from logs." },
    { id: "t4-19-efcore-performance",
      track: 4, number: 19, minutes: 40, status: "planned",
      title: "EF Core: Compiled Queries and Performance",
      scope: "Query compilation cost, compiled queries, bulk operations, ExecuteUpdate/ExecuteDelete, batching." },
    { id: "t4-20-efcore-migrations",
      track: 4, number: 20, minutes: 40, status: "planned",
      title: "EF Core: Migrations",
      scope: "Model snapshots, generated SQL, data migrations, and migrations you can safely run against production." },
    { id: "t4-21-raw-sql-and-dapper",
      track: 4, number: 21, minutes: 40, status: "planned",
      title: "Raw SQL Escape Hatches and Dapper",
      scope: "FromSql, parameterisation, when Dapper wins, and running both in one codebase without chaos." },
    { id: "t4-22-caching-in-memory",
      track: 4, number: 22, minutes: 40, status: "planned",
      title: "In-Memory Caching",
      scope: "IMemoryCache, HybridCache in .NET 9+, sizing, eviction, and the cache stampede." },
    { id: "t4-23-distributed-cache-redis",
      track: 4, number: 23, minutes: 40, status: "planned",
      title: "Distributed Caching and Redis",
      scope: "IDistributedCache, Redis data types, serialisation, connection management, and failure modes." },
    { id: "t4-24-cache-invalidation",
      track: 4, number: 24, minutes: 40, status: "planned",
      title: "Cache Invalidation Strategies",
      scope: "TTL, write-through, write-behind, cache-aside, tag-based invalidation, and staleness budgets." },
    { id: "t4-25-nosql",
      track: 4, number: 25, minutes: 40, status: "planned",
      title: "NoSQL Where It Genuinely Fits",
      scope: "Document/key-value/wide-column/graph, access-pattern-first modelling, and the cases SQL still wins." },

    /* -- Track 5: Production Systems and Architecture ------------------------- */
    { id: "t5-01-layered-architecture",
      track: 5, number: 1, minutes: 45, status: "planned",
      title: "Layered Architecture",
      scope: "The classic N-tier split, dependency direction, and where it genuinely breaks down." },
    { id: "t5-02-clean-architecture",
      track: 5, number: 2, minutes: 45, status: "planned",
      title: "Clean / Onion Architecture",
      scope: "Dependency inversion at the architecture level, the ports-and-adapters idea, and its real ceremony cost." },
    { id: "t5-03-vertical-slice",
      track: 5, number: 3, minutes: 45, status: "planned",
      title: "Vertical Slice Architecture",
      scope: "Organising by feature, coupling trade-offs, and why it often beats layers in practice." },
    { id: "t5-04-hexagonal",
      track: 5, number: 4, minutes: 45, status: "planned",
      title: "Hexagonal Architecture",
      scope: "Ports, adapters, the domain at the centre, and testing without infrastructure." },
    { id: "t5-05-modular-monolith",
      track: 5, number: 5, minutes: 45, status: "planned",
      title: "The Modular Monolith",
      scope: "Module boundaries, enforced isolation, shared database vs schema-per-module, and the migration path out." },
    { id: "t5-06-microservices",
      track: 5, number: 6, minutes: 45, status: "planned",
      title: "Microservices — and When They Are Overkill",
      scope: "Service boundaries, the distributed-systems tax, data ownership, and an honest cost/benefit account." },
    { id: "t5-07-cqrs",
      track: 5, number: 7, minutes: 45, status: "planned",
      title: "CQRS With and Without MediatR",
      scope: "Splitting reads from writes, when a mediator helps, when it is indirection theatre, and hand-rolled dispatch." },
    { id: "t5-08-ddd-building-blocks",
      track: 5, number: 8, minutes: 45, status: "planned",
      title: "DDD Building Blocks",
      scope: "Entities, value objects, aggregates, aggregate roots, repositories, domain services, and ubiquitous language." },
    { id: "t5-09-domain-events",
      track: 5, number: 9, minutes: 45, status: "planned",
      title: "Domain Events",
      scope: "Raising events inside an aggregate, dispatch timing, and keeping side effects out of the domain model." },
    { id: "t5-10-event-driven-design",
      track: 5, number: 10, minutes: 45, status: "planned",
      title: "Event-Driven Design",
      scope: "Events vs commands, choreography vs orchestration, eventual consistency, and event schema evolution." },
    { id: "t5-11-message-brokers",
      track: 5, number: 11, minutes: 45, status: "planned",
      title: "Message Brokers",
      scope: "Queues vs topics, RabbitMQ/Kafka/Azure Service Bus models, delivery guarantees, consumer groups, DLQs." },
    { id: "t5-12-outbox-pattern",
      track: 5, number: 12, minutes: 45, status: "planned",
      title: "The Outbox Pattern",
      scope: "The dual-write problem, transactional outbox, relay processing, and de-duplication downstream." },
    { id: "t5-13-sagas",
      track: 5, number: 13, minutes: 45, status: "planned",
      title: "Sagas and Long-Running Processes",
      scope: "Orchestration vs choreography, compensating actions, state persistence, and timeout handling." },
    { id: "t5-14-idempotency",
      track: 5, number: 14, minutes: 45, status: "planned",
      title: "Idempotency",
      scope: "Why at-least-once delivery forces it, idempotency keys, storage design, and making a payment endpoint safe." },
    { id: "t5-15-distributed-locks",
      track: 5, number: 15, minutes: 45, status: "planned",
      title: "Distributed Locks",
      scope: "Why they are harder than they look, Redis/DB-based locks, fencing tokens, lease expiry, and safer alternatives." },
    { id: "t5-16-resilience-retry",
      track: 5, number: 16, minutes: 45, status: "planned",
      title: "Retry and Exponential Backoff With Jitter",
      scope: "Transient vs permanent failures, backoff maths, jitter strategies, and how naive retries amplify an outage." },
    { id: "t5-17-circuit-breaker",
      track: 5, number: 17, minutes: 45, status: "planned",
      title: "Circuit Breakers, Bulkheads, Timeouts, Fallbacks",
      scope: "Polly v8 resilience pipelines, state transitions, isolation, and composing strategies in the right order." },
    { id: "t5-18-rate-limiting",
      track: 5, number: 18, minutes: 45, status: "planned",
      title: "Rate Limiting and Throttling",
      scope: "Fixed/sliding window, token bucket, concurrency limiter, .NET rate-limiting middleware, and per-tenant limits." },
    { id: "t5-19-load-shedding",
      track: 5, number: 19, minutes: 45, status: "planned",
      title: "Backpressure and Load Shedding",
      scope: "Queue depth as a signal, shedding cheaply, degradation modes, and protecting the system from itself." },
    { id: "t5-20-authn-vs-authz",
      track: 5, number: 20, minutes: 45, status: "planned",
      title: "Authentication vs Authorisation, Defined Precisely",
      scope: "The two questions, where each belongs, identity vs claims vs permissions, and the vocabulary used correctly." },
    { id: "t5-21-cookie-auth",
      track: 5, number: 21, minutes: 45, status: "planned",
      title: "Cookie Authentication",
      scope: "Cookie flags, sessions, sliding expiration, sign-out semantics, and when cookies beat tokens." },
    { id: "t5-22-jwt",
      track: 5, number: 22, minutes: 45, status: "planned",
      title: "JWT: Structure, Signing, Validation",
      scope: "Header/payload/signature, HS vs RS vs ES, validation parameters, alg confusion, and what a JWT does *not* protect." },
    { id: "t5-23-refresh-tokens",
      track: 5, number: 23, minutes: 45, status: "planned",
      title: "Refresh Token Rotation",
      scope: "Short access tokens, rotation, reuse detection, revocation lists, and secure client-side storage." },
    { id: "t5-24-oauth2",
      track: 5, number: 24, minutes: 45, status: "planned",
      title: "OAuth2 Grant Types",
      scope: "Authorisation code + PKCE, client credentials, device code, deprecated implicit/password grants, and scopes." },
    { id: "t5-25-oidc",
      track: 5, number: 25, minutes: 45, status: "planned",
      title: "OpenID Connect",
      scope: "ID tokens vs access tokens, discovery, JWKS and key rotation, userinfo, and federated sign-out." },
    { id: "t5-26-api-keys-and-mtls",
      track: 5, number: 26, minutes: 45, status: "planned",
      title: "API Keys and mTLS",
      scope: "Key issuance, hashing at rest, scoping, rotation, client certificate auth, and service-to-service identity." },
    { id: "t5-27-authorization-models",
      track: 5, number: 27, minutes: 45, status: "planned",
      title: "Role vs Claims vs Permission vs Policy-Based Authorisation",
      scope: "The four models compared precisely, requirement handlers, and resource-based authorisation." },
    { id: "t5-28-rbac-design",
      track: 5, number: 28, minutes: 45, status: "planned",
      title: "Designing a Full RBAC Model",
      scope: "Users, roles, permissions, scopes, hierarchy, delegation, the data model, and caching authorisation decisions." },
    { id: "t5-29-owasp-top-10",
      track: 5, number: 29, minutes: 45, status: "planned",
      title: "OWASP Top 10 With .NET Mitigations",
      scope: "Each category mapped to concrete ASP.NET Core defences and the misconfigurations that reintroduce it." },
    { id: "t5-30-injection-attacks",
      track: 5, number: 30, minutes: 45, status: "planned",
      title: "SQL Injection, XSS, CSRF, SSRF, Mass Assignment",
      scope: "How each attack actually works, a working exploit, and the .NET-specific fix for each." },
    { id: "t5-31-crypto-basics",
      track: 5, number: 31, minutes: 45, status: "planned",
      title: "Hashing vs Encryption, and Secret Storage",
      scope: "Password hashing, salts, HMAC, symmetric vs asymmetric, key management, and what never to invent yourself." },
    { id: "t5-32-data-protection",
      track: 5, number: 32, minutes: 45, status: "planned",
      title: "ASP.NET Core Data Protection",
      scope: "The key ring, purposes, key persistence across instances, and the \"cookies invalid after deploy\" incident." },
    { id: "t5-33-multi-tenancy",
      track: 5, number: 33, minutes: 45, status: "planned",
      title: "Multi-Tenancy",
      scope: "Tenant resolution, isolation models (row/schema/database), noisy neighbours, and cross-tenant leak prevention." },
    { id: "t5-34-structured-logging",
      track: 5, number: 34, minutes: 45, status: "planned",
      title: "Logging Done Right",
      scope: "Structured logging, Serilog, levels, message templates, sampling, and what must never be logged." },
    { id: "t5-35-correlation-ids",
      track: 5, number: 35, minutes: 45, status: "planned",
      title: "Correlation IDs and Request Context",
      scope: "Propagating identity across services, Activity, log scopes, and reconstructing a request from logs." },
    { id: "t5-36-metrics",
      track: 5, number: 36, minutes: 45, status: "planned",
      title: "Metrics and Monitoring",
      scope: "Counters/gauges/histograms, RED and USE methods, System.Diagnostics.Metrics, dashboards, and alert design." },
    { id: "t5-37-opentelemetry",
      track: 5, number: 37, minutes: 45, status: "planned",
      title: "OpenTelemetry and Distributed Tracing",
      scope: "Spans, context propagation, instrumentation, exporters, sampling, and reading a trace end to end." },
    { id: "t5-38-unit-testing",
      track: 5, number: 38, minutes: 45, status: "planned",
      title: "Unit Testing",
      scope: "xUnit, arrange/act/assert, test naming, fakes vs mocks vs stubs, and tests that survive refactoring." },
    { id: "t5-39-integration-testing",
      track: 5, number: 39, minutes: 45, status: "planned",
      title: "Integration Testing With WebApplicationFactory",
      scope: "In-memory hosting, overriding services, auth in tests, and testing the real pipeline." },
    { id: "t5-40-testcontainers",
      track: 5, number: 40, minutes: 45, status: "planned",
      title: "Testcontainers and Test Data Strategy",
      scope: "Real databases in tests, fixtures, seeding, isolation between tests, and keeping the suite fast." },
    { id: "t5-41-docker",
      track: 5, number: 41, minutes: 45, status: "planned",
      title: "Docker for .NET",
      scope: "Layered images, multi-stage builds, chiselled/distroless bases, image size, and container-aware runtime config." },
    { id: "t5-42-cicd-and-deployment",
      track: 5, number: 42, minutes: 45, status: "planned",
      title: "CI/CD, Migrations in a Pipeline, Zero-Downtime Releases",
      scope: "Pipeline stages, expand/contract migrations, blue-green and rolling deploys, and safe rollback." },

    /* -- Track 6: Data Structures, Algorithms, and Interview Problems --------- */
    { id: "t6-01-complexity-from-scratch",
      track: 6, number: 1, minutes: 40, status: "planned",
      title: "Complexity Analysis From Scratch",
      scope: "Counting operations, deriving Big-O rather than recalling it, amortised cost, and space complexity." },
    { id: "t6-02-complexity-in-practice",
      track: 6, number: 2, minutes: 40, status: "planned",
      title: "Complexity of the BCL",
      scope: "Real costs of List, Dictionary, HashSet, SortedSet, LINQ operators, and string operations." },
    { id: "t6-03-arrays-and-hashing",
      track: 6, number: 3, minutes: 40, status: "planned",
      title: "Pattern: Arrays and Hashing",
      scope: "Frequency maps, seen-sets, trading space for time, and the problems this pattern silently solves." },
    { id: "t6-04-two-pointers",
      track: 6, number: 4, minutes: 40, status: "planned",
      title: "Pattern: Two Pointers",
      scope: "Opposite-end and same-direction pointers, sorted-array exploitation, and in-place partitioning." },
    { id: "t6-05-sliding-window",
      track: 6, number: 5, minutes: 40, status: "planned",
      title: "Pattern: Sliding Window",
      scope: "Fixed and variable windows, the shrink condition, and recognising \"contiguous subarray/substring\"." },
    { id: "t6-06-prefix-sums",
      track: 6, number: 6, minutes: 40, status: "planned",
      title: "Pattern: Prefix Sums",
      scope: "Range queries in O(1), prefix-sum + hashmap for subarray targets, and 2-D prefix sums." },
    { id: "t6-07-binary-search",
      track: 6, number: 7, minutes: 40, status: "planned",
      title: "Pattern: Binary Search and Its Disguises",
      scope: "Boundary search, search on answer space, lo/hi invariants, and off-by-one elimination." },
    { id: "t6-08-stacks",
      track: 6, number: 8, minutes: 40, status: "planned",
      title: "Pattern: Stacks",
      scope: "LIFO problems, matching pairs, expression evaluation, and simulating recursion." },
    { id: "t6-09-monotonic-stack",
      track: 6, number: 9, minutes: 40, status: "planned",
      title: "Pattern: Monotonic Stack",
      scope: "Next-greater/smaller element, histogram problems, and recognising the \"nearest boundary\" shape." },
    { id: "t6-10-queues-and-deques",
      track: 6, number: 10, minutes: 40, status: "planned",
      title: "Pattern: Queues and Monotonic Deques",
      scope: "FIFO processing, sliding-window maximum, and Queue<T>/LinkedList<T> in C#." },
    { id: "t6-11-linked-lists",
      track: 6, number: 11, minutes: 40, status: "planned",
      title: "Pattern: Linked Lists",
      scope: "Pointer manipulation, dummy heads, reversal, cycle detection (Floyd), and merge patterns." },
    { id: "t6-12-trees-traversal",
      track: 6, number: 12, minutes: 40, status: "planned",
      title: "Trees and Traversal",
      scope: "Binary trees, DFS orders, BFS by level, recursive vs iterative, and building traversal intuition." },
    { id: "t6-13-bst",
      track: 6, number: 13, minutes: 40, status: "planned",
      title: "Binary Search Trees",
      scope: "Ordering invariant, search/insert/delete, in-order = sorted, and balance (why AVL/red-black exist)." },
    { id: "t6-14-tree-dp",
      track: 6, number: 14, minutes: 40, status: "planned",
      title: "Pattern: Tree Recursion and Tree DP",
      scope: "Returning state up the tree, path problems, diameter, and lowest common ancestor." },
    { id: "t6-15-tries",
      track: 6, number: 15, minutes: 40, status: "planned",
      title: "Tries",
      scope: "Prefix trees, node design in C#, autocomplete, word search, and memory trade-offs." },
    { id: "t6-16-heaps",
      track: 6, number: 16, minutes: 40, status: "planned",
      title: "Heaps and Priority Queues",
      scope: "Heap invariant, PriorityQueue<TElement,TPriority>, top-K, and k-way merge." },
    { id: "t6-17-graphs-representation",
      track: 6, number: 17, minutes: 40, status: "planned",
      title: "Graphs: Representation and Traversal",
      scope: "Adjacency list vs matrix, BFS, DFS, connected components, and grid-as-graph." },
    { id: "t6-18-topological-sort",
      track: 6, number: 18, minutes: 40, status: "planned",
      title: "Pattern: Topological Sort",
      scope: "Dependency ordering, Kahn's algorithm, DFS-based ordering, and cycle detection." },
    { id: "t6-19-shortest-path",
      track: 6, number: 19, minutes: 40, status: "planned",
      title: "Shortest Path",
      scope: "BFS on unweighted graphs, Dijkstra, Bellman-Ford, and choosing between them." },
    { id: "t6-20-union-find",
      track: 6, number: 20, minutes: 40, status: "planned",
      title: "Union-Find (Disjoint Set)",
      scope: "Union by rank, path compression, near-constant amortised cost, and connectivity/MST problems." },
    { id: "t6-21-backtracking",
      track: 6, number: 21, minutes: 40, status: "planned",
      title: "Pattern: Backtracking",
      scope: "The choose/explore/unchoose skeleton, pruning, and subsets/permutations/combinations/N-Queens." },
    { id: "t6-22-greedy",
      track: 6, number: 22, minutes: 40, status: "planned",
      title: "Pattern: Greedy",
      scope: "Exchange argument, proving a greedy choice is safe, and when greedy quietly fails." },
    { id: "t6-23-dp-foundations",
      track: 6, number: 23, minutes: 40, status: "planned",
      title: "Dynamic Programming: Memoisation → Tabulation → Space Optimisation",
      scope: "State definition, recurrence derivation, and the mechanical path from recursion to O(1) space." },
    { id: "t6-24-dp-patterns",
      track: 6, number: 24, minutes: 40, status: "planned",
      title: "DP Pattern Catalogue",
      scope: "Knapsack, LIS, LCS, edit distance, grid paths, interval DP, and bitmask DP." },
    { id: "t6-25-intervals",
      track: 6, number: 25, minutes: 40, status: "planned",
      title: "Pattern: Intervals",
      scope: "Sorting by start/end, merging, overlap detection, meeting rooms, and sweep line." },
    { id: "t6-26-bit-manipulation",
      track: 6, number: 26, minutes: 40, status: "planned",
      title: "Pattern: Bit Manipulation",
      scope: "Masks, XOR tricks, counting bits, subsets via bitmask, and BitOperations in .NET." },
    { id: "t6-27-matrix",
      track: 6, number: 27, minutes: 40, status: "planned",
      title: "Pattern: Matrix Traversal",
      scope: "Rotation, spiral order, in-place transforms, and flood fill." },
    { id: "t6-28-csharp-interview-idioms",
      track: 6, number: 28, minutes: 40, status: "planned",
      title: "C#-Specific Interview Idioms",
      scope: "Which BCL type to reach for under time pressure, LINQ vs loops in interviews, and idiomatic fast writing." }
  ]
};
