// AuditLogGenerator.cs — an incremental source generator.
//
// It looks for classes marked [AuditLog] and writes, for each one, a partial
// method that formats every public property. That is the same job the reflective
// validator in t1-31 did at runtime, moved to build time.
//
// Three things make it INCREMENTAL rather than the old ISourceGenerator:
//   1. It registers a PIPELINE of transformations, not a single Execute method.
//   2. The predicate is a cheap syntax-only test, run on every keystroke.
//   3. The transform's output is a small, EQUATABLE value — so when the model
//      does not change, the compiler reuses the cached output and does not run
//      the generation step at all.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Ledger.Generators
{
    /// <summary>
    /// A plain, equatable model. This is the single most important design rule:
    /// never let a Symbol or a SyntaxNode reach the pipeline's cached values, or
    /// caching cannot work and the generator runs on every keystroke.
    /// </summary>
    internal sealed record AuditModel(
        string Namespace,
        string ClassName,
        string Accessibility,
        EquatableArray<string> PropertyNames);

    /// <summary>An array with value equality, so the record above compares by contents.</summary>
    internal readonly struct EquatableArray<T> : IEquatable<EquatableArray<T>>
        where T : IEquatable<T>
    {
        private readonly T[] _items;
        public EquatableArray(T[] items) => _items = items;
        public int Count => _items?.Length ?? 0;
        public T[] AsArray() => _items ?? Array.Empty<T>();

        public bool Equals(EquatableArray<T> other)
        {
            var a = AsArray();
            var b = other.AsArray();
            if (a.Length != b.Length) return false;
            for (var i = 0; i < a.Length; i++)
                if (!a[i].Equals(b[i])) return false;
            return true;
        }

        public override bool Equals(object? obj) => obj is EquatableArray<T> o && Equals(o);

        public override int GetHashCode()
        {
            var hash = 17;
            foreach (var item in AsArray()) hash = hash * 31 + item.GetHashCode();
            return hash;
        }
    }

    [Generator]
    public sealed class AuditLogGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable

namespace Ledger.App
{
    /// <summary>Marks a partial class for a generated audit-log formatter.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
    internal sealed class AuditLogAttribute : global::System.Attribute
    {
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // STEP 1: contribute the attribute itself, so the consumer does not
            // have to declare it. RegisterPostInitializationOutput runs once and
            // cannot depend on user code.
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("AuditLogAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            // STEP 2: find candidates. ForAttributeWithMetadataName is the fast
            // path — the compiler indexes attribute usages, so this does not walk
            // every syntax node.
            var models = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Ledger.App.AuditLogAttribute",
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => ToModel(ctx))
                .Where(static m => m is not null)
                .Select(static (m, _) => m!);

            // STEP 3: generate. Runs only for models that actually changed.
            context.RegisterSourceOutput(models, static (spc, model) =>
            {
                var source = Render(model);
                spc.AddSource($"{model.ClassName}.Audit.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }

        private static AuditModel? ToModel(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol symbol) return null;

            var names = symbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                            !p.IsStatic && !p.IsIndexer && p.GetMethod is not null)
                .Select(p => p.Name)
                .OrderBy(n => n, StringComparer.Ordinal)
                .ToArray();

            return new AuditModel(
                symbol.ContainingNamespace.IsGlobalNamespace
                    ? ""
                    : symbol.ContainingNamespace.ToDisplayString(),
                symbol.Name,
                symbol.DeclaredAccessibility == Accessibility.Public ? "public" : "internal",
                new EquatableArray<string>(names));
        }

        private static string Render(AuditModel model)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            var indent = "";
            if (model.Namespace.Length > 0)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
                indent = "    ";
            }

            sb.AppendLine($"{indent}{model.Accessibility} partial class {model.ClassName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    /// <summary>Generated at build time from {model.PropertyNames.Count} public properties.</summary>");
            sb.AppendLine($"{indent}    public string ToAuditLog()");
            sb.AppendLine($"{indent}    {{");

            if (model.PropertyNames.Count == 0)
            {
                sb.AppendLine($"{indent}        return \"{model.ClassName} {{ }}\";");
            }
            else
            {
                sb.AppendLine($"{indent}        var sb = new global::System.Text.StringBuilder();");
                sb.AppendLine($"{indent}        sb.Append(\"{model.ClassName} {{ \");");
                var names = model.PropertyNames.AsArray();
                for (var i = 0; i < names.Length; i++)
                {
                    var sep = i == 0 ? "" : ", ";
                    sb.AppendLine($"{indent}        sb.Append(\"{sep}{names[i]}=\").Append(this.{names[i]});");
                }
                sb.AppendLine($"{indent}        sb.Append(\" }}\");");
                sb.AppendLine($"{indent}        return sb.ToString();");
            }

            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (model.Namespace.Length > 0) sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
